services:
  mi-mongo-dc:
    container_name: mi-mongo-dc
    image: mongo
    networks:
      - mi-red-dc
    volumes:
      - mi-volumen-dc:/data/db
    stdin_open: true
    tty: true

  mi-mongo-express-dc:
    container_name: mi-mongo-express-dc
    image: mongo-express
    networks:
      - mi-red-dc
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mi-mongo-dc
    stdin_open: true
    tty: true


#docker network create  mi-red-dc
networks:
  mi-red-dc:

#docker volume create mi-volumen-dc
volumes:
  mi-volumen-dc: