services:
  mi-mysql-dc:
    container_name: mi-mysql-dc
    image: mysql
    networks:
      - mi-mysql-red-dc
    volumes:
      - mi-mysql-vol-dc:/data/db
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    stdin_open: true
    tty: true

  mi-dashboard-dc:
    container_name: mi-dashboard-dc
    image: phpmyadmin
    networks:
      - mi-mysql-red-dc
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mi-mysql-dc
    
    stdin_open: true
    tty: true


#docker network create --subnet 172.100.0.0/16 mi-mysql-red-dc
networks:
  mi-mysql-red-dc:
    ipam:
      driver: default # --driver bridge
      config:
        - subnet: 172.25.0.0/16

#docker volume create mi-mysql-vol-dc
volumes:
  mi-mysql-vol-dc: